#!/usr/bin/env bash
# Install and configure HAproxy on my lb-01 server.
apt-get -y install haproxy

# edit config file
server_config=\
"
frontend  firdaus-alx-frontend
        bind *:80
        mode http
        default_backend firdaus-alx-backend
backend firdaus-alx-backend
        balance roundrobin
        server 914-web-01 34.138.32.248 check
        server 914-web-02 3.226.74.205 check
"
 echo "$server_config" >> /etc/haproxy/haproxy.cfg

 # enable haproxy to be started by init script

 echo "ENABLED=1" >> /etc/default/haproxy

 sudo service haproxy restart